---
apiVersion: v1
kind: Pod
metadata:
 name: testapp-pod
 labels:
  app:testapp
 spec:
  containers:
   name: testapp-container
   image: busybox
   command: ["sh", "-c", "echo This is kubernetes && sleep 3600"]
