---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myip
  labels:
    app: myip
    ver: v1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myip
      ver: v1
  template:
    metadata:
      labels:
        app: myip
        ver: v1
    spec:
      containers:
        - name: myip
          image: your_dockerhub_id/myip:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
