---

apiVersion: v1
kind: Service
metadata:
  name: myip-svc
  labels:
    name: myip-svc
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: myip
    ver: v1  
